// ═══════════════════════════════════════════════
//  FATE ENGINE — CARD DATA  (cards.js)
//
//  RARITY ORDER (worst to best):
//  trash / common / uncommon / rare / super_rare / epic / legendary / divine / supreme
//
//  STARS: trash=0  common=1  uncommon=2  rare=3  super_rare=3  epic=4  legendary=5  divine=5  supreme=5
// ═══════════════════════════════════════════════


// ── CHARACTER CARDS ─────────────────────────────

const CHARACTER_CARDS = [

  // — ABILITIES —
  { type:"Ability", icon:"💨", name:"Mild Breeze", rarity:"trash", stars:0,
    desc:"You can produce a very slight breeze from your hands. Useful for cooling soup. That is the only use anyone has found." },
  { type:"Ability", icon:"⚡", name:"Static Pulse", rarity:"common", stars:1,
    desc:"You can release bursts of electrical energy from your palms. Enough to stun a man, or charge a dead phone." },
  { type:"Ability", icon:"🌊", name:"Tidecall", rarity:"uncommon", stars:2,
    desc:"Water within 30 meters bends to your will. Rivers slow, rain lifts upward, and tears freeze mid-cheek." },
  { type:"Ability", icon:"🔥", name:"Soulflame", rarity:"rare", stars:3,
    desc:"You burn — not with fire, but with purpose. Wounds close faster. Fear burns away. So do lies." },
  { type:"Ability", icon:"🌿", name:"Verdant Surge", rarity:"super_rare", stars:3,
    desc:"Plant matter grows at your command. A seed becomes a tree in seconds. Roots obey. Thorns listen. Forests remember your face." },
  { type:"Ability", icon:"🌀", name:"Void Step", rarity:"epic", stars:4,
    desc:"Once per hour you may step sideways through space. No sound. No trace. Just the faint smell of absence." },
  { type:"Ability", icon:"☀️", name:"Sunborn", rarity:"legendary", stars:5,
    desc:"You were kissed by something ancient. Light bends around you. Darkness refuses to stay. Gods notice." },
  { type:"Ability", icon:"🌌", name:"The Eternal Breath", rarity:"divine", stars:5,
    desc:"You exhale and the world listens. Storms halt mid-turn. Fires freeze. The dying take one more breath. Whatever you speak in this state becomes briefly, terrifyingly true." },
  { type:"Ability", icon:"✦", name:"Unmaking Touch", rarity:"supreme", stars:5,
    desc:"You can unmake things. Not destroy them — unmake them. Return them to before they existed. You have used this once. You will not speak of what it was." },
  { type:"Ability", icon:"🧊", name:"Still Air", rarity:"common", stars:1,
    desc:"You can make a room go absolutely silent. Useful in libraries. Terrifying in arguments." },
  { type:"Ability", icon:"🌑", name:"Umbral Touch", rarity:"uncommon", stars:2,
    desc:"Whatever you hold in darkness becomes invisible. The darkness doesn't need to be total. Just enough." },
  { type:"Ability", icon:"🩸", name:"Blood Pact", rarity:"rare", stars:3,
    desc:"A wound made by your hand becomes a contract. The injured party cannot willingly harm you for seven days." },
  { type:"Ability", icon:"💀", name:"Necrospeak", rarity:"epic", stars:4,
    desc:"The recently dead can hear you. They rarely answer. When they do, they are always right." },
  { type:"Ability", icon:"⚗️", name:"The Transmutation", rarity:"legendary", stars:5,
    desc:"You may change one thing about reality per moon. Small things. The size of a lie. The color of grief. The weight of a name." },

  // — TRAITS —
  { type:"Trait", icon:"😴", name:"Chronic Lateness", rarity:"trash", stars:0,
    desc:"You are always late. Not fashionably late. Not strategically late. Just late. You have missed things. You will miss more things. You have made peace with this, which is itself a kind of power." },
  { type:"Trait", icon:"🦴", name:"Ironblood", rarity:"common", stars:1,
    desc:"Your bones are harder than they should be. Doctors are confused. You are not." },
  { type:"Trait", icon:"🧠", name:"Eidetic Memory", rarity:"uncommon", stars:2,
    desc:"You forget nothing. Every face, every insult, every map you glanced at in a dream. A blessing and a curse." },
  { type:"Trait", icon:"👁️", name:"The Third Sight", rarity:"rare", stars:3,
    desc:"You see intent before action. Not the future — just a half-second delay the world hasn't corrected yet." },
  { type:"Trait", icon:"🔮", name:"Resonant Soul", rarity:"super_rare", stars:3,
    desc:"You vibrate at a frequency others can feel but not name. Animals trust you immediately. People take longer but deeper. Instruments detune in your presence." },
  { type:"Trait", icon:"🌒", name:"Shade-born", rarity:"epic", stars:4,
    desc:"Shadows do not fall on you correctly. They follow a different you — one that moves with more confidence." },
  { type:"Trait", icon:"⚖️", name:"Sovereign Will", rarity:"legendary", stars:5,
    desc:"You cannot be compelled. Not by magic, not by torture, not by love. Your choices are entirely your own. This is lonelier than it sounds." },
  { type:"Trait", icon:"🌟", name:"The Chosen Bearing", rarity:"divine", stars:5,
    desc:"Something in how you carry yourself makes others believe — not that you are great, but that you were made for exactly this moment. Whatever this moment is. They are always right." },
  { type:"Trait", icon:"∞", name:"The Unbroken Thread", rarity:"supreme", stars:5,
    desc:"You are connected to every version of yourself across every possible life. When you make a decision, all other versions of you know it was right — even if you don't yet." },
  { type:"Trait", icon:"🕯️", name:"Cursed Luck", rarity:"common", stars:1,
    desc:"Things go wrong for you, then go right, then go wrong in ways that save your life. You've stopped questioning it." },
  { type:"Trait", icon:"🌿", name:"Root Memory", rarity:"uncommon", stars:2,
    desc:"Plants remember you. They lean toward you. Old forests whisper your name to each other when you pass." },
  { type:"Trait", icon:"🐺", name:"Apex Instinct", rarity:"rare", stars:3,
    desc:"You know when something is about to attack. Not through logic. Through something older. You're never wrong." },

  // — ITEMS —
  { type:"Item", icon:"🧦", name:"Left Sock", rarity:"trash", stars:0,
    desc:"A sock. It is slightly damp. You do not know why. It fits your left foot perfectly and your right foot not at all. You keep it anyway." },
  { type:"Item", icon:"📿", name:"Waystone Necklace", rarity:"common", stars:1,
    desc:"Always points home. The definition of home is debated." },
  { type:"Item", icon:"🗡️", name:"Forgetful Blade", rarity:"uncommon", stars:2,
    desc:"A knife that makes wounds forget to hurt. Useful in many ways. Dangerous in most of them." },
  { type:"Item", icon:"📖", name:"The Unwritten Book", rarity:"rare", stars:3,
    desc:"A leather journal with 300 blank pages. Whatever you write in it by morning has happened by noon." },
  { type:"Item", icon:"🏺", name:"The Sealed Urn", rarity:"super_rare", stars:3,
    desc:"Contains something. The seal is intact. The urn is warm to the touch. It hums at night. Every scholar who has examined it recommends not opening it. None of them agree on why." },
  { type:"Item", icon:"⌛", name:"Borrowed Hour", rarity:"epic", stars:4,
    desc:"A pocket watch that runs backward. Break it to undo the last hour of your life. It only works once. You've been carrying it for years." },
  { type:"Item", icon:"🪞", name:"Mirror of Becoming", rarity:"legendary", stars:5,
    desc:"Shows you who you could have been. Some people can't put it down. Some smash it immediately. Both are correct." },
  { type:"Item", icon:"📜", name:"The First Law", rarity:"divine", stars:5,
    desc:"A scroll that predates writing. The words on it are not in any language but are understood immediately by whoever reads them. What it says changes based on what you most need to hear. It has never been wrong. It has never been kind." },
  { type:"Item", icon:"✦", name:"The Last Key", rarity:"supreme", stars:5,
    desc:"A key that opens anything. Not locks — anything. Questions. Wounds. Sealed fates. Closed minds. It was made for one door. That door has not been found. You are not sure you want to find it." },
  { type:"Item", icon:"🎭", name:"The Hollow Mask", rarity:"rare", stars:3,
    desc:"Wear it to become someone else. Not in appearance — in soul. People believe you are them completely. You start to, as well." },
  { type:"Item", icon:"🧲", name:"The Binding Coin", rarity:"uncommon", stars:2,
    desc:"Flip it to make a deal. The coin ensures both parties keep their word. It has never been wrong. It has never been kind." },
  { type:"Item", icon:"🗺️", name:"Dead Man's Map", rarity:"common", stars:1,
    desc:"A map of a place that doesn't exist yet. The roads look familiar." },

  // — FAMILIARS —
  { type:"Familiar", icon:"🐛", name:"Gerald", rarity:"trash", stars:0,
    desc:"A caterpillar. Gerald is his name; you did not choose it — he arrived already named. He does nothing. He goes nowhere quickly. He is, inexplicably, always there when you need company." },
  { type:"Familiar", icon:"🐈‍⬛", name:"The Nameless Cat", rarity:"common", stars:1,
    desc:"Follows you. You did not invite it. It has saved your life twice and you still don't know its name." },
  { type:"Familiar", icon:"🦊", name:"Ember Fox", rarity:"uncommon", stars:2,
    desc:"A small fox with a perpetually warm tail. Loyal, clever, and absolutely uninterested in your enemies." },
  { type:"Familiar", icon:"🦅", name:"The Pale Hawk", rarity:"rare", stars:3,
    desc:"Flies ahead. Returns with information it shouldn't have. Never explains how." },
  { type:"Familiar", icon:"🐍", name:"The Whispering Serpent", rarity:"super_rare", stars:3,
    desc:"Coils around your wrist and speaks directly into your thoughts. It knows things it should not know. It tells you things you are not sure you should hear. It has never lied. It has never told the whole truth either." },
  { type:"Familiar", icon:"🌙", name:"Moonshade Hound", rarity:"epic", stars:4,
    desc:"A wolf made of the space between stars. Only visible at night. Only loyal when it chooses to be." },
  { type:"Familiar", icon:"🐉", name:"Ashling", rarity:"legendary", stars:5,
    desc:"A dragon the size of a cat who insists it is not a dragon. Do not argue. It will remember." },
  { type:"Familiar", icon:"🕊️", name:"The White Messenger", rarity:"divine", stars:5,
    desc:"A bird that appears only in moments of genuine crisis. It carries nothing. It delivers nothing. Its presence alone changes what happens next. No one has ever seen it leave." },
  { type:"Familiar", icon:"✦", name:"The Unnamed", rarity:"supreme", stars:5,
    desc:"It has no form you can describe after seeing it. It is always with you. You feel it most in moments of impossible choice. It never tells you what to do — but when you choose, it is satisfied. Or it isn't. You can tell the difference." },
  { type:"Familiar", icon:"🦋", name:"The Oracle Moth", rarity:"uncommon", stars:2,
    desc:"Lands on the thing you need to pay attention to. Has never been wrong. Is deeply inconvenient about it." },

  // — TITLES —
  { type:"Title", icon:"🥄", name:"The One With the Spoon", rarity:"trash", stars:0,
    desc:"You had a spoon at a critical moment and someone noticed. The title has followed you since. It means nothing. People remember it." },
  { type:"Title", icon:"🕊️", name:"Peacemaker", rarity:"common", stars:1,
    desc:"People calm down around you. Wars have ended because you walked into the room. You're tired." },
  { type:"Title", icon:"🎯", name:"The Marked", rarity:"uncommon", stars:2,
    desc:"Something powerful chose you for a reason it has not shared. People can sense it. Most step aside." },
  { type:"Title", icon:"🔱", name:"Twice-Judged", rarity:"rare", stars:3,
    desc:"You have stood before a court of some kind — mortal, divine, or otherwise — and walked out both times." },
  { type:"Title", icon:"🧩", name:"Wildcard", rarity:"super_rare", stars:3,
    desc:"You don't fit any prophecy. You don't fit any category. This makes you the most dangerous thing in the room." },
  { type:"Title", icon:"👑", name:"The Undefeated", rarity:"epic", stars:4,
    desc:"You have not yet lost. Whether through skill, luck, or the quiet mercy of fate — you are still standing." },
  { type:"Title", icon:"⚰️", name:"The One Who Returns", rarity:"legendary", stars:5,
    desc:"You have died. Officially. There is paperwork. You are inconveniently alive and no one knows what to do with you." },
  { type:"Title", icon:"🌟", name:"The Anointed", rarity:"divine", stars:5,
    desc:"Something chose you. Not a person, not a god in any name you recognise — something older. It did not ask. You did not agree. The weight of it sits between your shoulders and has never left." },
  { type:"Title", icon:"∞", name:"The Last One", rarity:"supreme", stars:5,
    desc:"There is a version of events in which you are the last thing standing. Not because you are the strongest. Because everything else ends first. You did not choose this. You have not yet decided what to do with it." },

  // — RACES —
  { type:"Race", icon:"🐀", name:"Greykin", rarity:"trash", stars:0,
    desc:"A people descended from scavengers, or so their enemies say. They are resourceful, deeply practical, and have survived every empire that looked down on them. Their cities are ugly and indestructible." },
  { type:"Race", icon:"🌿", name:"Verdathi", rarity:"common", stars:1,
    desc:"A people who grow slowly and live long. Their skin hardens with age. Their elders are indistinguishable from bark. They find this dignified." },
  { type:"Race", icon:"🌊", name:"Tidewrought", rarity:"uncommon", stars:2,
    desc:"Coastal people shaped by generations of deep-water diving. Their lungs hold more than they should. They hear tides in their sleep. Landlocked cities make them anxious in ways they can't explain." },
  { type:"Race", icon:"🔥", name:"Cindreborn", rarity:"rare", stars:3,
    desc:"Descended from those who survived a fire that should have killed everything. They run warm. They don't scar. They are immune to smoke and have complicated feelings about flames." },
  { type:"Race", icon:"⚡", name:"Stormkind", rarity:"super_rare", stars:3,
    desc:"A people born during storms, marked by static in their hair and a faint hum others can feel but not hear. They attract lightning. Not metaphorically — literally. They have learned to use this." },
  { type:"Race", icon:"👁️", name:"The Eyeless", rarity:"epic", stars:4,
    desc:"A race that lost their eyes generations ago and developed something else in their place. They perceive intent directly. They cannot be lied to. Conversations with them are deeply uncomfortable." },
  { type:"Race", icon:"🌑", name:"Umbral", rarity:"legendary", stars:5,
    desc:"Born in places where light never reaches. Your eyes reflect nothing. You navigate by feeling the shape of darkness, which has more texture than most people imagine." },
  { type:"Race", icon:"🌌", name:"The Starwalkers", rarity:"divine", stars:5,
    desc:"A people who do not age, do not tire, and do not die of natural causes. They were the first race. They remember things that predate memory itself. They do not speak of those things. They have agreed among themselves never to." },
  { type:"Race", icon:"✦", name:"Stardrift", rarity:"supreme", stars:5,
    desc:"No one knows where they came from. They arrived over centuries, always alone, always already speaking the local language. They age in reverse and have no word for home. Some believe they are not from this world. They neither confirm nor deny this." },

];


// ── WORLD CARDS ──────────────────────────────────

const WORLD_CARDS = [

  // — BIOMES —
  { type:"Biome", icon:"🌾", name:"The Ashpastures", rarity:"trash", stars:0,
    desc:"A vast flat expanse of grey soil that grows one crop: a tasteless but nutritious grain that requires no tending and survives anything. It is deeply unpleasant to live near. It has saved millions of lives." },
  { type:"Biome", icon:"🌊", name:"The Drowned Shelf", rarity:"common", stars:1,
    desc:"A shallow sea covering what was once a great plain. Ancient towers still rise above the waterline. Things live in them." },
  { type:"Biome", icon:"🌋", name:"The Ashfields", rarity:"uncommon", stars:2,
    desc:"A continent of hardened lava and ember-soil where heat-resistant crops grow in volcanic ash. The sky is always orange at noon." },
  { type:"Biome", icon:"🏜️", name:"The Glass Desert", rarity:"rare", stars:3,
    desc:"Sand fused into glass by an ancient catastrophe. The surface reflects everything. At noon, the entire desert becomes a mirror and can be seen from space." },
  { type:"Biome", icon:"🌲", name:"The Mirrorwood", rarity:"super_rare", stars:3,
    desc:"A forest where every tree grows an exact reflection of the one opposite it. Navigation is impossible. Compasses spin. People return changed." },
  { type:"Biome", icon:"🌌", name:"The Veilsteppe", rarity:"epic", stars:4,
    desc:"A grassland that exists partially in another plane. At dusk, you can see through the ground to a sky below your feet. Travelers go mad or transcendent. Rarely in-between." },
  { type:"Biome", icon:"🌿", name:"The Rootdeep", rarity:"legendary", stars:5,
    desc:"A subterranean ecosystem built around the roots of ancient trees. Entire civilizations have never seen sunlight. They worship the roots as gods." },
  { type:"Biome", icon:"🌟", name:"The Singing Peaks", rarity:"divine", stars:5,
    desc:"A mountain range that produces music. Not wind-through-rock, not illusion — actual music, composed, structured, evolving. It has been playing for longer than any civilization has existed. No one knows what it is saying. Several have devoted their lives to finding out." },
  { type:"Biome", icon:"🌀", name:"The Wound", rarity:"supreme", stars:5,
    desc:"A region where reality was torn and never healed. Physics works differently here. Time is nonlinear. Armies have entered and emerged centuries apart." },
  { type:"Biome", icon:"❄️", name:"The Still Tundra", rarity:"common", stars:1,
    desc:"A frozen expanse so silent that speech feels wrong. Hunters here communicate in hand signs passed down for 40 generations." },

  // — FACTIONS —
  { type:"Faction", icon:"📋", name:"The Bureau of Weights", rarity:"trash", stars:0,
    desc:"A bureaucratic body responsible for standardising measurements across three kingdoms. They have no political power, no military, and no significance beyond their mandate. They are incorruptible. This makes them, quietly, the most dangerous institution in the region." },
  { type:"Faction", icon:"⚔️", name:"The Ironless", rarity:"common", stars:1,
    desc:"A warrior clan that refuses to use metal weapons. They are considered primitive. They have never been conquered." },
  { type:"Faction", icon:"⚜️", name:"The Pale Compact", rarity:"uncommon", stars:2,
    desc:"A merchants' alliance that secretly controls grain supply across six nations. They have never fought a war. They have ended eleven." },
  { type:"Faction", icon:"🔮", name:"The Unbound Circle", rarity:"rare", stars:3,
    desc:"Mages who rejected institutional magic and now practice in secret. Their spells are unpredictable. Their loyalty is to knowledge, not kingdoms." },
  { type:"Faction", icon:"🌿", name:"The Green Debt", rarity:"super_rare", stars:3,
    desc:"Druids who believe all civilization owes a debt to the land. They collect. Slowly. Patiently. With interest." },
  { type:"Faction", icon:"🕯️", name:"Keepers of the Last Name", rarity:"epic", stars:4,
    desc:"A secret order that memorizes the names of every person who has ever died without record. They believe unnamed dead become monsters. They may be right." },
  { type:"Faction", icon:"🌑", name:"The Hollow Court", rarity:"legendary", stars:5,
    desc:"A government that rules from a city no one can find. Their edicts arrive by raven. Their taxes are collected by agents who appear, take what is owed, and vanish. No one has ever refused twice." },
  { type:"Faction", icon:"🌟", name:"The Order of the Unspoken", rarity:"divine", stars:5,
    desc:"They have taken a vow of silence so complete that they have forgotten language. They communicate in other ways. They know things that words cannot contain. They are sought out by those who need answers that cannot be asked." },
  { type:"Faction", icon:"✦", name:"The Architects", rarity:"supreme", stars:5,
    desc:"No one has met them. Their work is everywhere — in the geometry of old cities, in the way certain roads converge, in the proportions of structures that have stood for millennia. Someone built the world with intent. It was probably them." },

  // — MATERIALS —
  { type:"Material", icon:"💩", name:"Bog Silt", rarity:"trash", stars:0,
    desc:"Thick, foul-smelling sediment dredged from swamp beds. Useless for construction, agriculture, or craft. Surprisingly effective as a pest deterrent. No one is sure why." },
  { type:"Material", icon:"🔩", name:"Ashiron", rarity:"common", stars:1,
    desc:"Metal smelted from volcanic rock. Cheaper than steel, twice as brittle, but it never rusts and holds an edge for decades." },
  { type:"Material", icon:"🌿", name:"Breathmoss", rarity:"uncommon", stars:2,
    desc:"A moss that produces oxygen in extreme quantities. Cities in sealed caverns are built around it. It dies if it hears music." },
  { type:"Material", icon:"⚡", name:"Stormthread", rarity:"rare", stars:3,
    desc:"Fiber harvested from the edge of lightning strikes. Clothing woven from it conducts electricity harmlessly around the body. Extremely difficult to produce. Extremely sought after." },
  { type:"Material", icon:"🦴", name:"Deepbone", rarity:"super_rare", stars:3,
    desc:"Fossilized remains of creatures that lived before recorded history. Nearly indestructible. Something about it makes animals uneasy." },
  { type:"Material", icon:"💎", name:"Voidglass", rarity:"epic", stars:4,
    desc:"A black transparent mineral that absorbs light. Objects placed inside it become invisible and weightless. The mineral itself is impossible to cut." },
  { type:"Material", icon:"✨", name:"Mirrorstone", rarity:"legendary", stars:5,
    desc:"A mineral that reflects not light but fate. Look into it and see the most likely version of your death. Banned in most nations. Collected obsessively by others." },
  { type:"Material", icon:"🌟", name:"Celestite", rarity:"divine", stars:5,
    desc:"A material that exists partly outside physical space. Objects made from it cast no shadow, leave no trace, and cannot be destroyed by any force currently understood. There are seven known pieces. Six are accounted for." },
  { type:"Material", icon:"∞", name:"The Unnamed Ore", rarity:"supreme", stars:5,
    desc:"Found once, in a crater that predates the planet. It cannot be cut, melted, or shaped. It cannot be moved without its permission, which it grants or withholds seemingly at random. It is studied constantly. It is understood not at all." },

  // — SPECIES —
  { type:"Species", icon:"🐛", name:"The Crawling Veil", rarity:"trash", stars:0,
    desc:"Small, translucent, and harmless. They infest grain stores, eat nothing of value, and produce a faint bioluminescence at night. Farmers tolerate them. Children keep them as pets. They serve no purpose anyone has identified." },
  { type:"Species", icon:"🦇", name:"The Echoveil", rarity:"common", stars:1,
    desc:"A blind species that navigates entirely by sound. Their cities are built for hearing, not sight. They find silence threatening and are never, ever quiet." },
  { type:"Species", icon:"🌿", name:"Rootkin", rarity:"uncommon", stars:2,
    desc:"Plant-humanoid hybrids that photosynthesize. They sleep standing in sunlight. They do not eat. They are deeply patient and slightly smug about it." },
  { type:"Species", icon:"🔮", name:"Glassborn", rarity:"rare", stars:3,
    desc:"Creatures with translucent skin through which their organs are clearly visible. They are considered deeply beautiful in some cultures, deeply unsettling in others. Both are right." },
  { type:"Species", icon:"👁️", name:"The Woven", rarity:"super_rare", stars:3,
    desc:"Humanoids born with threads of visible light connecting them to nearby people. The threads show emotion. They cannot lie. They are exhausting to be around." },
  { type:"Species", icon:"🌊", name:"Tidecallers", rarity:"epic", stars:4,
    desc:"Aquatic humanoids who can survive on land for up to 40 years before needing to return to deep water. Many have forgotten they are not human. The sea has not forgotten them." },
  { type:"Species", icon:"⚰️", name:"The Twice-Born", rarity:"legendary", stars:5,
    desc:"A species that dies once in youth and resurrects changed. The second life is longer. The memories of death remain. They rule most of the oldest empires." },
  { type:"Species", icon:"🌌", name:"The Dreaming", rarity:"divine", stars:5,
    desc:"A species that exists primarily in sleep. Their waking bodies are still and barely breathing. Their dreaming selves move through a world layered beneath this one. They have been dreaming the same collective dream for ten thousand years. Some believe the waking world is a side effect of it." },
  { type:"Species", icon:"✦", name:"The Formless", rarity:"supreme", stars:5,
    desc:"They have no consistent shape. They are not shapeshifters — they simply have not settled. Each encounter with one is with something slightly different. They are very old. They remember the world before it had edges. They are not sure the edges were an improvement." },

  // — PAST —
  { type:"Past", icon:"🌾", name:"The Forgettable Century", rarity:"trash", stars:0,
    desc:"One hundred years in which, by all accounts, nothing of note happened. Crops grew. Weather was mild. No wars. No plagues. Historians call it the Forgettable Century. Nobody knows what caused it or how to bring it back." },
  { type:"Past", icon:"🌑", name:"The Long Night", rarity:"common", stars:1,
    desc:"For seventeen years the sun did not rise. No one remembers why. People who were born during it are slightly different — calmer in darkness, unnerved by noon. They rarely speak of it." },
  { type:"Past", icon:"⚔️", name:"The War of Correct Names", rarity:"uncommon", stars:2,
    desc:"A century-long conflict fought entirely over language. What things were called determined what they were allowed to be. It ended when both sides ran out of words they agreed on." },
  { type:"Past", icon:"💀", name:"The Culling Plague", rarity:"rare", stars:3,
    desc:"A disease that killed selectively — only the cruel, only the kind, only the old, accounts vary. The survivors built very different societies depending on which version killed theirs." },
  { type:"Past", icon:"🏛️", name:"The First Empire", rarity:"super_rare", stars:3,
    desc:"Ten thousand years ago a single civilisation ruled every continent. No one knows what ended it. Their roads still exist. Their locks still work. Their language is still spoken in dreams by people who have never learned it." },
  { type:"Past", icon:"✨", name:"The Age of Answered Prayers", rarity:"epic", stars:4,
    desc:"For one hundred years, every sincere prayer was answered. Exactly as asked. With no interpretation. The theological consequences took centuries to untangle and some argue they still haven't been." },
  { type:"Past", icon:"🌟", name:"The Time Before Names", rarity:"legendary", stars:5,
    desc:"A period so distant that language had not yet separated things from each other. Everything was everything. The world remembers it the way a dreamer remembers a dream — as a feeling, not a fact." },
  { type:"Past", icon:"🌌", name:"The Visitation", rarity:"divine", stars:5,
    desc:"Something came. It did not speak, did not act, did not harm. It was simply present for forty days across every point on the planet simultaneously. Then it left. Every religion alive today was founded in the century that followed. None of them agree on what it was." },
  { type:"Past", icon:"🌀", name:"The Unmaking", rarity:"supreme", stars:5,
    desc:"Something tried to end the world. It almost succeeded. The records of what it was were deliberately destroyed by the people who stopped it. The method they used was also destroyed. There are those who spend their lives trying to find out why." },

  // — EVENTS —
  { type:"Event", icon:"🌾", name:"The Failed Harvest", rarity:"trash", stars:0,
    desc:"Crops failed this season across a minor province. It happens. Aid is coming slowly. People are irritable. Local officials are issuing statements. Nothing about this is unusual except that it is the third time in four years, and no one has yet asked why." },
  { type:"Event", icon:"🌊", name:"The Retreating Sea", rarity:"common", stars:1,
    desc:"The ocean on the eastern coast has pulled back forty miles in the past decade. The exposed seabed is rich, strange, and full of structures that should not exist. People are moving in. The sea is still retreating." },
  { type:"Event", icon:"👑", name:"The Succession of Three", rarity:"uncommon", stars:2,
    desc:"A throne is contested by three claimants, each with equal legal claim, each with a faction, each convinced the other two are wrong. The kingdom functions normally. The tension does not." },
  { type:"Event", icon:"💀", name:"The Quiet Deaths", rarity:"rare", stars:3,
    desc:"People are dying in their sleep across six cities, in sequence, one city at a time, moving south. No cause has been found. Each victim reported the same dream the night before. No one has written the dream down." },
  { type:"Event", icon:"🌋", name:"The Awakening of Vel Morroth", rarity:"super_rare", stars:3,
    desc:"A dormant volcano at the centre of the known world has begun to breathe. Not erupt — breathe. Volcanologists measure the rhythm. Priests argue about what it means. Everyone agrees it means something." },
  { type:"Event", icon:"🔮", name:"The Opening of the Sealed Archive", rarity:"epic", stars:4,
    desc:"A library that has been locked for three hundred years has opened on its own. The books inside are written in a language no one recognises, in handwriting that matches no known scholar, dated fifty years from now." },
  { type:"Event", icon:"✨", name:"The Return of the Stardrift", rarity:"legendary", stars:5,
    desc:"After two centuries of absence, members of the Stardrift race have begun appearing again, always alone, always in places of significance, never explaining where they have been. They seem younger than when they left. They ask a lot of questions about what has changed." },
  { type:"Event", icon:"🌟", name:"The Second Visitation", rarity:"divine", stars:5,
    desc:"It has returned. The same presence, the same silence, the same forty-day duration — but this time it is not passive. It is waiting for something. Every living being on the planet feels this in their chest at night and cannot explain it." },
  { type:"Event", icon:"🌀", name:"The Unravelling", rarity:"supreme", stars:5,
    desc:"Something is coming undone. Not violently — slowly, at the edges. People near borders and coastlines report that things look slightly wrong. Animals are moving inland. Dreams are blurring into waking. The seams of the world are visible to those who look. Most choose not to look." },

];
